runtime: python

env: flex

runtime_config:
    python_version: 3

network:
  session_affinity: true

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 7

entrypoint: gunicorn --worker-class eventlet -w 1 app:app
